export interface Product {
  id: string
  brand: string
  name: string
  image: string
  type: string
  capacity: string
  energyLabel: string
  features: string[]
  price?: string
}

export const productCatalog: Record<string, Product[]> = {
  daikin: [
    {
      id: "daikin-perfera",
      brand: "Daikin",
      name: "Daikin Perfera",
      image: "/images/products/daikin-perfera-wit.webp",
      type: "Split-unit",
      capacity: "2.5kW",
      energyLabel: "A+++",
      features: ["Fluisterstil", "WiFi control", "Luchtzuivering"],
    },
    {
      id: "daikin-perfera-vloer",
      brand: "Daikin",
      name: "Daikin Perfera Vloermodel",
      image: "/images/products/Perfera-vloermodel-left.webp",
      type: "Vloermodel",
      capacity: "3.5kW",
      energyLabel: "A+++",
      features: ["Vloermodel", "3D luchtstroom", "Onecta App"],
    },
    {
      id: "daikin-stylish-wit",
      brand: "Daikin",
      name: "Daikin Stylish Wit",
      image: "/images/products/daikin-stylish-wit.webp",
      type: "Designer Split",
      capacity: "2.5kW",
      energyLabel: "A+++",
      features: ["Design model", "Coanda effect", "Intelligent eye"],
    },
    {
      id: "daikin-stylish-zwart",
      brand: "Daikin",
      name: "Daikin Stylish Zwart",
      image: "/images/products/daikin-stylish-zwart.webp",
      type: "Designer Split",
      capacity: "3.5kW",
      energyLabel: "A+++",
      features: ["Premium black design", "Grid eye sensor", "Whisper quiet"],
    },
    {
      id: "daikin-emura-wit",
      brand: "Daikin",
      name: "Daikin Emura 3 Wit",
      image: "/images/products/daikin-emura-wit.webp",
      type: "Premium Split",
      capacity: "3.5kW",
      energyLabel: "A+++",
      features: ["Premium design", "2-zone motion sensor", "Flash Streamer"],
    },
    {
      id: "daikin-comfora",
      brand: "Daikin",
      name: "Daikin Comfora",
      image: "/images/products/daikin-comfora-right.webp",
      type: "Split-unit",
      capacity: "2.5kW",
      energyLabel: "A++",
      features: ["Betaalbaar", "Betrouwbaar", "Onecta App"],
    }
  ],
  "mitsubishi-electric": [
    {
      id: "mitsubishi-msz-ln25",
      brand: "Mitsubishi Electric",
      name: "MSZ-LN25VG Diamond",
      image: "/images/products/Mitsubishi heavy indus/Mitsubishi-titanium-zs-wft-1.webp",
      type: "Premium Split",
      capacity: "2.5kW",
      energyLabel: "A+++",
      features: ["3D i-see sensor", "Plasma Quad Plus", "Hyper Heating"],
    },
    {
      id: "mitsubishi-msz-ap35",
      brand: "Mitsubishi Electric",
      name: "MSZ-AP35VG",
      image: "/images/products/Mitsubishi heavy indus/Mitsubishi-titanium-zs-wft.webp",
      type: "Split-unit",
      capacity: "3.5kW",
      energyLabel: "A+++",
      features: ["Compact design", "MELCloud WiFi", "Weekly timer"],
    },
    {
      id: "mitsubishi-vloermodel",
      brand: "Mitsubishi Electric",
      name: "MFZ Vloermodel",
      image: "/images/products/Mitsubishi heavy indus/Mitsubishi-aircowebwinkel-vloermodel.webp",
      type: "Vloermodel",
      capacity: "3.5kW",
      energyLabel: "A+++",
      features: ["Vloermodel", "Silent mode", "Dual barrier coating"],
    },
    {
      id: "mitsubishi-srk50",
      brand: "Mitsubishi Electric",
      name: "SRK50ZS-W",
      image: "/images/products/Mitsubishi heavy indus/srk50zs-wf-wit-single-split-airco-wandmodel-2.5-3.5-5kw-1.webp",
      type: "Split-unit",
      capacity: "5.0kW",
      energyLabel: "A++",
      features: ["Krachtig", "Replace Technology", "Auto diagnostics"],
    },
    {
      id: "mitsubishi-heavy-titanium",
      brand: "Mitsubishi Electric",
      name: "Heavy Industries Titanium",
      image: "/images/products/Mitsubishi heavy indus/ZSX-T-510x512.webp",
      type: "Split-unit",
      capacity: "2.5kW",
      energyLabel: "A++",
      features: ["Titanium coating", "Reliable", "Easy maintenance"],
    },
    {
      id: "mitsubishi-vloer-srf",
      brand: "Mitsubishi Electric",
      name: "SRF-35 Vloerunit",
      image: "/images/products/Mitsubishi heavy indus/Mitsubishi-Heavy-SRF-35-ZS-W-Vloer-unit-35-kW-Exclusief-buiten-unit.webp",
      type: "Vloermodel",
      capacity: "3.5kW",
      energyLabel: "A+++",
      features: ["Vloerunit", "Stijlvol design", "Dual vane"],
    }
  ],
  samsung: [
    {
      id: "samsung-wind-free-comfort",
      brand: "Samsung",
      name: "Wind-Free Comfort",
      image: "/images/products/samsung/windfreeComfort/WindFree Comfort_S2_Front_Web_RGB.webp",
      type: "Split-unit",
      capacity: "2.5kW",
      energyLabel: "A+++",
      features: ["Wind-Free cooling", "AI Auto Comfort", "PM 1.0 filter"],
    },
    {
      id: "samsung-luzon",
      brand: "Samsung",
      name: "LUZON",
      image: "/images/products/samsung/luzon/Luzon_S2_Front_Web_RGB.webp",
      type: "Split-unit",
      capacity: "3.5kW",
      energyLabel: "A++",
      features: ["Fast cooling", "Triple Protector", "Easy filter"],
    },
    {
      id: "samsung-wind-free-elite",
      brand: "Samsung",
      name: "Wind-Free Elite",
      image: "/images/products/samsung/windfreeElite/WindFree Elite_S2_Front_Web_RGB.webp",
      type: "Premium Split",
      capacity: "3.5kW",
      energyLabel: "A+++",
      features: ["Premium Wind-Free", "Motion detect sensor", "SmartThings"],
    },
    {
      id: "samsung-wind-free-avant-black",
      brand: "Samsung",
      name: "Wind-Free Avant Black",
      image: "/images/products/samsung/windreeAvantBlack/WindFree Avant Black_Front_Web_RGB.webp",
      type: "Designer Split",
      capacity: "3.5kW",
      energyLabel: "A+++",
      features: ["Black design", "Wind-Free", "Smart control"],
    },
    {
      id: "samsung-360-cassette",
      brand: "Samsung",
      name: "360 Cassette",
      image: "/images/products/samsung/casette/360 Cassette - Rond - Front - Web.webp",
      type: "Cassette",
      capacity: "5.2kW",
      energyLabel: "A++",
      features: ["360° luchtstroom", "Bladeless design", "Quiet operation"],
    },
    {
      id: "samsung-wind-free-comfort-left",
      brand: "Samsung",
      name: "Wind-Free Comfort Silver",
      image: "/images/products/samsung/windfreeComfort/WindFree Comfort_S2_Left_Web_RGB.webp",
      type: "Split-unit",
      capacity: "2.5kW",
      energyLabel: "A+++",
      features: ["PM 1.0 filter", "Good Sleep mode", "Wind-Free cooling"],
    }
  ],
  lg: [
    {
      id: "lg-artcool-mirror",
      brand: "LG",
      name: "ARTCOOL Mirror",
      image: "/images/products/lg-artcool-mirror.webp",
      type: "Designer Split",
      capacity: "3.5kW",
      energyLabel: "A+++",
      features: ["Mirror design", "ThinQ", "UVnano"],
    },
    {
      id: "lg-standard-plus",
      brand: "LG",
      name: "Standard Plus",
      image: "/images/products/rac-eu-standard-plus-.webp",
      type: "Split-unit",
      capacity: "2.5kW",
      energyLabel: "A++",
      features: ["Dual Inverter", "Fast cooling", "Low noise"],
    },
    {
      id: "lg-dualcool-premium",
      brand: "LG",
      name: "DUALCOOL Premium",
      image: "/images/products/LG-dualcool-indoor-premium.webp",
      type: "Split-unit",
      capacity: "3.5kW",
      energyLabel: "A+++",
      features: ["Dual Inverter", "Ocean Black Fin", "ThinQ WiFi"],
    },
    {
      id: "lg-artcool-black",
      brand: "LG",
      name: "ARTCOOL Black",
      image: "/images/products/rac-eu-lg-artcool-black.webp",
      type: "Designer Split",
      capacity: "2.5kW",
      energyLabel: "A+++",
      features: ["Black glass design", "Ocean Black Protection", "Smart Diagnosis"],
    },
    {
      id: "lg-premium",
      brand: "LG",
      name: "Premium Deluxe",
      image: "/images/products/rac-eu-lg-premium.webp",
      type: "Premium Split",
      capacity: "3.5kW",
      energyLabel: "A+++",
      features: ["Premium design", "Plasmaster Ionizer+", "Air purifying"],
    },
    {
      id: "lg-dualcool-deluxe",
      brand: "LG",
      name: "DUALCOOL Deluxe",
      image: "/images/products/LG-dualcool-indoor-premium-1.webp",
      type: "Split-unit",
      capacity: "5.0kW",
      energyLabel: "A+++",
      features: ["Powerful cooling", "4-way swing", "Inverter V"],
    }
  ],
  toshiba: [
    {
      id: "toshiba-seiya-plus",
      brand: "Toshiba",
      name: "Seiya Plus",
      image: "/images/products/Seiya-plus-wit-vooraanzicht_12_11zon.webp",
      type: "Split-unit",
      capacity: "2.5kW",
      energyLabel: "A++",
      features: ["Quiet operation", "Weekly timer", "Self-cleaning"],
    },
    {
      id: "toshiba-haori-zwart",
      brand: "Toshiba",
      name: "HAORI Zwart",
      image: "/images/products/Haori-zwart-vooraanzicht_3_11zon.webp",
      type: "Designer Split",
      capacity: "3.5kW",
      energyLabel: "A+++",
      features: ["Fabric design", "Ultra quiet", "PM 2.5 filter"],
    },
    {
      id: "toshiba-haori-grijs",
      brand: "Toshiba",
      name: "HAORI Grijs",
      image: "/images/products/Haori-grijs-links_19_11zon.webp",
      type: "Designer Split",
      capacity: "2.5kW",
      energyLabel: "A+++",
      features: ["Grey fabric", "Whisper quiet", "HADA Care"],
    },
    {
      id: "toshiba-daiseikai",
      brand: "Toshiba",
      name: "Daiseikai 10",
      image: "/images/products/Daiseikai 10-Wit-vooraanzicht_4_11zon.webp",
      type: "Premium Split",
      capacity: "3.5kW",
      energyLabel: "A+++",
      features: ["Top efficiency", "Air purifying", "WiFi ready"],
    },
    {
      id: "toshiba-vloermodel",
      brand: "Toshiba",
      name: "Console Vloermodel",
      image: "/images/products/toshiba-console-vloermodel-wit_13_11zon.webp",
      type: "Vloermodel",
      capacity: "5.0kW",
      energyLabel: "A++",
      features: ["Vloerunit", "Twin Rotary compressor", "Wide operation range"],
    },
    {
      id: "toshiba-kazumi-plus",
      brand: "Toshiba",
      name: "Kazumi Plus Black",
      image: "/images/products/Kazumi-plus-Black-vooraanzicht_6_11zon.webp",
      type: "Split-unit",
      capacity: "2.5kW",
      energyLabel: "A++",
      features: ["Black design", "R32 refrigerant", "Auto restart"],
    }
  ],
  "mitsubishi-heavy": [
    {
      id: "mhi-srk25",
      brand: "Mitsubishi Heavy Industries",
      name: "SRK25ZS-W",
      image: "/images/products/mhi-srk.jpg",
      type: "Split-unit",
      capacity: "2.5kW",
      energyLabel: "A++",
      features: ["Allergen Clear", "Silent mode", "3D Auto"],
    },
    {
      id: "mhi-srk35",
      brand: "Mitsubishi Heavy Industries",
      name: "SRK35ZS-W Premium",
      image: "/images/products/mhi-premium.jpg",
      type: "Split-unit",
      capacity: "3.5kW",
      energyLabel: "A+++",
      features: ["Premium model", "Jet Air", "WiFi adapter ready"],
    },
    {
      id: "mhi-diamond",
      brand: "Mitsubishi Heavy Industries",
      name: "Diamond Series",
      image: "/images/products/mhi-diamond.jpg",
      type: "Premium Split",
      capacity: "3.5kW",
      energyLabel: "A+++",
      features: ["Elegant design", "Motion sensor", "Self-cleaning"],
    },
    {
      id: "mhi-multi-scm",
      brand: "Mitsubishi Heavy Industries",
      name: "SCM Multi-Split",
      image: "/images/products/mhi-multi.jpg",
      type: "Multi-split",
      capacity: "5.3kW",
      energyLabel: "A++",
      features: ["Flexible combinations", "High reliability", "Low noise"],
    },
    {
      id: "mhi-eco",
      brand: "Mitsubishi Heavy Industries",
      name: "Eco Hyper Inverter",
      image: "/images/products/mhi-eco.jpg",
      type: "Split-unit",
      capacity: "2.5kW",
      energyLabel: "A++",
      features: ["Eco-friendly", "Energy saving", "Timer function"],
    },
    {
      id: "mhi-premium-50",
      brand: "Mitsubishi Heavy Industries",
      name: "SRK50ZS-W Premium",
      image: "/images/products/mhi-premium-50.jpg",
      type: "Split-unit",
      capacity: "5.0kW",
      energyLabel: "A++",
      features: ["Large capacity", "Powerful mode", "Zone control"],
    }
  ],
  tosot: [
    {
      id: "tosot-vloermodel",
      brand: "Tosot",
      name: "Console Vloermodel",
      image: "/images/products/374-WTS-indoor-console-vloernmodel-tosot.webp",
      type: "Vloermodel",
      capacity: "3.5kW",
      energyLabel: "A++",
      features: ["Vloerunit", "I-Feel function", "Turbo mode"],
    },
    {
      id: "tosot-cosmo",
      brand: "Tosot",
      name: "COSMO",
      image: "/images/products/787-cosmo-indoor-vooraanzicht.webp",
      type: "Split-unit",
      capacity: "2.5kW",
      energyLabel: "A++",
      features: ["Budget friendly", "Low noise level", "WiFi optional"],
    },
    {
      id: "tosot-pular",
      brand: "Tosot",
      name: "PULAR",
      image: "/images/products/568-Pular-indoor-vooraanzicht.webp",
      type: "Split-unit",
      capacity: "3.5kW",
      energyLabel: "A+++",
      features: ["Premium quality", "7 fan speeds", "Intelligent defrost"],
    },
    {
      id: "tosot-pular-right",
      brand: "Tosot",
      name: "PULAR Plus",
      image: "/images/products/570-Pular-indoor-right.webp",
      type: "Split-unit",
      capacity: "5.0kW",
      energyLabel: "A++",
      features: ["High capacity", "Ultra quiet", "Smart control"],
    },
    {
      id: "tosot-cosmo-side",
      brand: "Tosot",
      name: "COSMO Deluxe",
      image: "/images/products/788-cosmo-indoor.webp",
      type: "Split-unit",
      capacity: "2.5kW",
      energyLabel: "A+",
      features: ["Affordable", "Basic functions", "5 year warranty"],
    },
    {
      id: "tosot-remote-console",
      brand: "Tosot",
      name: "Remote Console",
      image: "/images/products/375-WTS-remote-console-tosot.webp",
      type: "Accessoire",
      capacity: "N/A",
      energyLabel: "N/A",
      features: ["Smart remote", "LCD display", "Timer function"],
    }
  ],
  gree: [
    {
      id: "gree-clivia-wit",
      brand: "Gree",
      name: "Clivia Wit",
      image: "/images/products/724-clivia-wit-vooraanzicht.webp",
      type: "Split-unit",
      capacity: "2.5kW",
      energyLabel: "A++",
      features: ["G-Tech Inverter", "I-Feel", "Healthy filters"],
    },
    {
      id: "gree-clivia-zwart",
      brand: "Gree",
      name: "Clivia Zwart",
      image: "/images/products/712-clivia-zwart-vooraanzicht.webp",
      type: "Designer Split",
      capacity: "3.5kW",
      energyLabel: "A+++",
      features: ["Black design", "7 fan speeds", "WiFi control"],
    },
    {
      id: "gree-clivia-wit-schuin",
      brand: "Gree",
      name: "Clivia Premium Wit",
      image: "/images/products/723-clivia-wit-schuin.webp",
      type: "Split-unit",
      capacity: "2.5kW",
      energyLabel: "A++",
      features: ["Eco-friendly", "Cold Plasma", "Intelligent preheating"],
    },
    {
      id: "gree-clivia-zwart-schuin",
      brand: "Gree",
      name: "Clivia Premium Zwart",
      image: "/images/products/711-clivia-zwart-schuin.webp",
      type: "Premium Split",
      capacity: "3.5kW",
      energyLabel: "A+++",
      features: ["Premium black", "GMV technology", "Central control"],
    },
    {
      id: "gree-clivia-wit-zijkant",
      brand: "Gree",
      name: "Clivia Deluxe Wit",
      image: "/images/products/727-clivia-wit-zijkant.webp",
      type: "Split-unit",
      capacity: "5.0kW",
      energyLabel: "A++",
      features: ["Large capacity", "LED display", "Voice control ready"],
    },
    {
      id: "gree-clivia-zwart-zijkant",
      brand: "Gree",
      name: "Clivia Matt Black",
      image: "/images/products/710-clivia-zwart-zijkant.webp",
      type: "Designer Split",
      capacity: "3.5kW",
      energyLabel: "A+++",
      features: ["Matt black", "Turbo cooling", "Auto-clean"],
    }
  ]
}

export function getProductsByBrand(brandSlug: string): Product[] {
  return productCatalog[brandSlug] || []
}

export function getAllProducts(): Product[] {
  return Object.values(productCatalog).flat()
}

export function getProductById(productId: string): Product | undefined {
  const allProducts = getAllProducts()
  return allProducts.find(product => product.id === productId)
}